worker_processes auto;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    keepalive_timeout 65;

    client_body_timeout 10s;
    client_header_timeout 10s;
    server_tokens off;

    # Указываем DNS-резолвер Docker, чтобы Nginx заново опросил сеть при падении узла
    resolver 127.0.0.11 valid=2s;

    upstream backend_servers {
        server app-1:8080 max_fails=2 fail_timeout=3s;
        server app-2:8080 max_fails=2 fail_timeout=3s;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
            proxy_next_upstream_tries 3;
            proxy_next_upstream_timeout 5s;
        }
    }
}
